version: '3.4'

services:
  gateway.api:
    image: gatewayapi
    build:
      context: .
      dockerfile: Gateway.API/Dockerfile
    ports:
      - "5000:80"
    networks:
      - fitfrontier

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Users.API/Dockerfile
    networks:
      - fitfrontier
    container_name: users.api
    ports:
      - "5001:80"
    depends_on:
      - "users.database"

  crypto.api:
    image: cryptoapi
    build:
      context: .
      dockerfile: Crypto.API/Dockerfile
    networks:
      - fitfrontier
    container_name: crypto.api
    ports:
      - "5002:80"
    depends_on:
      - "crypto.database"

  users.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: users.database
    container_name: users.database
    environment: 
      - SA_PASSWORD=zaq1@WSX
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes:
      - users-db:/var/opt/mssql
    ports:
      - "6000:1433"
    networks:
      - fitfrontier

  crypto.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: crypto.database
    container_name: crypto.database
    environment: 
      - SA_PASSWORD=zaq1@WSX
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    volumes:
      - crypto-db:/var/opt/mssql
    ports:
      - "6001:1433"
    networks:
      - fitfrontier

networks:
  fitfrontier:
    external: true

volumes:
  users-db:
  crypto-db:
