version: '3.4'

services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: Users.API/Dockerfile
    networks:
      - fitfrontier
    container_name: users.api
    ports:
        - "5001:80"
    depends_on:
      - "users.database"

  crypto.api:
    image: ${DOCKER_REGISTRY-}cryptoapi
    build:
      context: .
      dockerfile: Crypto.API/Dockerfile
    ports:
        - "5002:80"
    networks:
      - fitfrontier

  users.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: users.database
    container_name: users.database
    environment: 
      - SA_PASSWORD:zaq1@WSX
      - ACCEPT_EULA:Y
      - MSSQL_PID=Developer
    volumes:
      - users-db:/var/opt/mssql
    ports:
        - "6000:1433"
    networks:
      - fitfrontier

  crypto.database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    hostname: crypto.database
    environment: 
      - SA_PASSWORD:zaq1@WSX
      - ACCEPT_EULA:Y
    ports:
      - "1434:1433"
    networks:
      - fitfrontier

networks:
  fitfrontier:
    external: true

volumes:
  users-db:
